services:
  ##################################
  # Stage0 Runbook API Service
  ##################################
  api:
    image: ghcr.io/agile-learning-institute/stage0_runbook_api:latest
    container_name: stage0_runbook_api
    restart: no
    ports:
      - "8083:8083"
    environment:
      API_PORT: 8083
      ENABLE_LOGIN: "true"
      LOGGING_LEVEL: "INFO"
      JWT_SECRET: ${JWT_SECRET:-}
      MOUNT_DIR: ${MOUNT_DIR:-}
      UI_HEADER: "Stage0 DEV Runbooks"
    volumes:
      - ./execution:/execution
      - ./runbooks:/runbooks
    profiles:
      - api
      - service

  ##################################
  # Stage0 Runbook SPA Service
  ##################################
  spa:
    image: ghcr.io/agile-learning-institute/stage0_runbook_spa:latest
    container_name: stage0_runbook_spa
    restart: no
    ports:
      - "8084:80"
    environment:
      API_HOST: api
      API_PORT: 8083
      IDP_LOGIN_URI: http://localhost:8084/login
    depends_on:
      api:
        condition: service_started
    profiles:
      - service
